### ISSUE TITLE
Trabalho avaliado, obrigado pela entrega!

### ISSUE THREAD

**Issue by lucasferreira** [paulorsimao/SATCare#1]
Jovens,

O tema do trabalho de vocês me agrada muito e a execução também ficou bem bacana.

A preocupação estética e também o fato de ter dois tipos/níveis de login foi um plus a mais. 

Senti falta de um dashboard pós login, alguns detalhes tipo no caso do admin ter as ultimas consultas pendentes ou listadas, no caso do usuário ter as aprovações e confirmações das solicitações dele e etc. Mas nada que vá afetar a nota de vocês.

Obrigado pela presença em sala de aula e até a próxima!

**Comment by paulorsimao** [comment]
Valeu Lucas, 

A medida que formos ganhando mais experiência, e talvez na disciplina de backend, iremos voltar a aprimorar esse trabalho.
